/**
 * City names per country for the register form's city picker.
 *
 * Data: `cities.json`, generated by `npm run cities:build`. Albania, Kosovo and
 * Montenegro list every town (dr5hn/countries-states-cities-database — © its
 * contributors, ODbL-1.0); every other country lists only its 20 largest
 * cities (GeoNames, CC BY 4.0), with the pinned "Other" covering the rest. Both
 * are credited in Settings (`settings.credits`).
 *
 * The JSON (~40 KB) is `require`d lazily on first use, so it is parsed only
 * when someone registers, never at app boot. A country with no city data
 * (tiny territories, city-states like Gibraltar or Vatican City) offers its
 * own name as the only city, so the picker never falls back to free text.
 */
import { COUNTRIES } from './countries';

type CityData = Record<string, readonly string[]>;

let data: CityData | null = null;

/**
 * Stored city when the user's town isn't listed. A stable English value (not
 * the translated label) so the backend sees one spelling in every locale.
 */
export const CITY_OTHER = 'Other';

/** Cities for a country, looked up by the English name the form stores. */
export function getCitiesForCountry(countryName: string): readonly string[] {
  const code = COUNTRIES.find((c) => c.name === countryName)?.code;
  if (!code) return [];
  data ??= require('./cities.json') as CityData;
  return data[code] ?? [countryName];
}
